#!/bin/csh
#PBS -q home-hopper
#PBS -N birtwistle_2007
#PBS -l nodes=1:ppn=8:gpu
#PBS -l walltime=10:00:00
#PBS -o /oasis/tscc/scratch/nlinden/MAPK_models/B_2007_out.txt
#PBS -e /oasis/tscc/scratch/nlinden/MAPK_models/B_2007_err.txt
#PBS -V
#PBS -M nlinden@ucsd.edu
#PBS -m abe
#PBS -A rangamani-hopper-gpu
module load cuda/11.2.0
cd /home/nlinden/multimodel-inference/src/MAPK/gsa
/home/nlinden/y/envs/pymc/bin/python gsa_sample.py birtwistle_2007 --analyze_params 

 --n_samples 256 --savedir /oasis/tscc/scratch/nlinden/MAPK_models/ --max_time 
exit 0