#!/bin/csh
#PBS -q home-hopper
#PBS -N Huang_Ferrell_1996
#PBS -l nodes=1:ppn=8
#PBS -l walltime=05:00:00
#PBS -o /oasis/tscc/scratch/nlinden/MAPK_models/HF_1996_out.txt
#PBS -e /oasis/tscc/scratch/nlinden/MAPK_models/HF_1996_err.txt
#PBS -V
#PBS -M nlinden@ucsd.edu
#PBS -m abe
#PBS -A rangamani-hopper-gpu
module load cuda/11.2.0
cd /home/nlinden/multimodel-inference/src/MAPK/gsa
/home/nlinden/y/envs/pymc/bin/python gsa_sample.py huang_ferrell_1996 --analyze_params MKK_tot,a3,k7,a4,d3,d10,d2,a2,d6,a8,a1,E2_tot,a7,a9,k5,a6,d1,d9,d5,k8,d8,k4,k6,k9,k3,d7,a10,MAPK_tot,k2,d4,a5,MKKK_tot,k10,MKKPase_tot,k1 --n_samples 256 --savedir /oasis/tscc/scratch/nlinden/MAPK_models/ --max_time 3000
exit 0
