#!/bin/csh
#PBS -q home-hopper
#PBS -N Kholodenko_2000
#PBS -l nodes=1:ppn=4:gpu
#PBS -l walltime=02:00:00
#PBS -o /oasis/tscc/scratch/nlinden/MAPK_models/K_2000_out.txt
#PBS -e /oasis/tscc/scratch/nlinden/MAPK_models/K_2000_err.txt
#PBS -V
#PBS -M nlinden@ucsd.edu
#PBS -m abe
#PBS -A rangamani-hopper-gpu
module load cuda/11.2.0
cd /home/nlinden/multimodel-inference/src/MAPK/gsa
/home/nlinden/y/envs/pymc/bin/python gsa_sample.py kholodenko_2000 --analyze_params K8,v10,v9,K7,K9,KI,MAPK_total,K10 --n_samples 256 --savedir /oasis/tscc/scratch/nlinden/MAPK_models/ --max_time 10000
exit 0