#!/bin/csh
#PBS -q home-hopper
#PBS -N ryu_2015
#PBS -l nodes=1:ppn=4:gpu
#PBS -l walltime=02:00:00
#PBS -o /oasis/tscc/scratch/nlinden/MAPK_models/R_2015_out.txt
#PBS -e /oasis/tscc/scratch/nlinden/MAPK_models/R_2015_err.txt
#PBS -V
#PBS -M nlinden@ucsd.edu
#PBS -m abe
#PBS -A rangamani-hopper-gpu
module load cuda/11.2.0
cd /home/nlinden/multimodel-inference/src/MAPK/gsa
/home/nlinden/y/envs/pymc/bin/python gsa_sample.py ryu_2015 --analyze_params D2,T_dusp,K_dusp,K2,dusp_ind --n_samples 256 --savedir /oasis/tscc/scratch/nlinden/MAPK_models/ --max_time 540
exit 0