#!/bin/csh
#PBS -q home-hopper
#PBS -N shin_2014
#PBS -l nodes=1:ppn=4:gpu
#PBS -l walltime=02:00:00
#PBS -o /oasis/tscc/scratch/nlinden/MAPK_models/S_2014_out.txt
#PBS -e /oasis/tscc/scratch/nlinden/MAPK_models/S_2014_err.txt
#PBS -V
#PBS -M nlinden@ucsd.edu
#PBS -m abe
#PBS -A rangamani-hopper-gpu
module load cuda/11.2.0
cd /home/nlinden/multimodel-inference/src/MAPK/gsa
/home/nlinden/y/envs/pymc/bin/python gsa_sample.py shin_2014 --analyze_params kc47,kc43,kd39,kc45,ERK_tot,ki39,kc41 --n_samples 256 --savedir /oasis/tscc/scratch/nlinden/MAPK_models/ --max_time 540
exit 0