#!/bin/csh
#PBS -q home-hopper
#PBS -N vonKriegsheim_2009
#PBS -l nodes=1:ppn=4:gpu
#PBS -l walltime=05:00:00
#PBS -o /oasis/tscc/scratch/nlinden/MAPK_models/VK_2009_out.txt
#PBS -e /oasis/tscc/scratch/nlinden/MAPK_models/VK_2009_err.txt
#PBS -V
#PBS -M nlinden@ucsd.edu
#PBS -m abe
#PBS -A rangamani-hopper-gpu
module load cuda/11.2.0
cd /home/nlinden/multimodel-inference/src/MAPK/gsa
/home/nlinden/y/envs/pymc/bin/python gsa_sample.py vonKriegsheim_2009 --analyze_params k42,k37,k4,k27,k45,k69,k30,k43,k48,k5,k14,k28,k39,k46,k63,k68,k55,k29,k41,k25,k7,,k13,k2,k40,k6,k18,k56,k32,k38,k10,k34 --n_samples 256 --savedir /oasis/tscc/scratch/nlinden/MAPK_models/ --max_time 3600
exit 0